/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LivraisonRouteImport } from './routes/livraison'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConseilsRouteImport } from './routes/conseils'
import { Route as CoffretSignatureRouteImport } from './routes/coffret-signature'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsScentlabRouteImport } from './routes/collections.scentlab'
import { Route as CollectionsHaqqiRouteImport } from './routes/collections.haqqi'
import { Route as BoutiqueProductSlugRouteImport } from './routes/boutique.$productSlug'

const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonRoute = LivraisonRouteImport.update({
  id: '/livraison',
  path: '/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilsRoute = ConseilsRouteImport.update({
  id: '/conseils',
  path: '/conseils',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffretSignatureRoute = CoffretSignatureRouteImport.update({
  id: '/coffret-signature',
  path: '/coffret-signature',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsScentlabRoute = CollectionsScentlabRouteImport.update({
  id: '/collections/scentlab',
  path: '/collections/scentlab',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHaqqiRoute = CollectionsHaqqiRouteImport.update({
  id: '/collections/haqqi',
  path: '/collections/haqqi',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueProductSlugRoute = BoutiqueProductSlugRouteImport.update({
  id: '/$productSlug',
  path: '/$productSlug',
  getParentRoute: () => BoutiqueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRouteWithChildren
  '/coffret-signature': typeof CoffretSignatureRoute
  '/conseils': typeof ConseilsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/livraison': typeof LivraisonRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/boutique/$productSlug': typeof BoutiqueProductSlugRoute
  '/collections/haqqi': typeof CollectionsHaqqiRoute
  '/collections/scentlab': typeof CollectionsScentlabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRouteWithChildren
  '/coffret-signature': typeof CoffretSignatureRoute
  '/conseils': typeof ConseilsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/livraison': typeof LivraisonRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/boutique/$productSlug': typeof BoutiqueProductSlugRoute
  '/collections/haqqi': typeof CollectionsHaqqiRoute
  '/collections/scentlab': typeof CollectionsScentlabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/boutique': typeof BoutiqueRouteWithChildren
  '/coffret-signature': typeof CoffretSignatureRoute
  '/conseils': typeof ConseilsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/livraison': typeof LivraisonRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/boutique/$productSlug': typeof BoutiqueProductSlugRoute
  '/collections/haqqi': typeof CollectionsHaqqiRoute
  '/collections/scentlab': typeof CollectionsScentlabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/boutique'
    | '/coffret-signature'
    | '/conseils'
    | '/contact'
    | '/faq'
    | '/livraison'
    | '/mentions-legales'
    | '/boutique/$productSlug'
    | '/collections/haqqi'
    | '/collections/scentlab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/boutique'
    | '/coffret-signature'
    | '/conseils'
    | '/contact'
    | '/faq'
    | '/livraison'
    | '/mentions-legales'
    | '/boutique/$productSlug'
    | '/collections/haqqi'
    | '/collections/scentlab'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/boutique'
    | '/coffret-signature'
    | '/conseils'
    | '/contact'
    | '/faq'
    | '/livraison'
    | '/mentions-legales'
    | '/boutique/$productSlug'
    | '/collections/haqqi'
    | '/collections/scentlab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  BoutiqueRoute: typeof BoutiqueRouteWithChildren
  CoffretSignatureRoute: typeof CoffretSignatureRoute
  ConseilsRoute: typeof ConseilsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LivraisonRoute: typeof LivraisonRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  CollectionsHaqqiRoute: typeof CollectionsHaqqiRoute
  CollectionsScentlabRoute: typeof CollectionsScentlabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison': {
      id: '/livraison'
      path: '/livraison'
      fullPath: '/livraison'
      preLoaderRoute: typeof LivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils': {
      id: '/conseils'
      path: '/conseils'
      fullPath: '/conseils'
      preLoaderRoute: typeof ConseilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffret-signature': {
      id: '/coffret-signature'
      path: '/coffret-signature'
      fullPath: '/coffret-signature'
      preLoaderRoute: typeof CoffretSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/scentlab': {
      id: '/collections/scentlab'
      path: '/collections/scentlab'
      fullPath: '/collections/scentlab'
      preLoaderRoute: typeof CollectionsScentlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/haqqi': {
      id: '/collections/haqqi'
      path: '/collections/haqqi'
      fullPath: '/collections/haqqi'
      preLoaderRoute: typeof CollectionsHaqqiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/$productSlug': {
      id: '/boutique/$productSlug'
      path: '/$productSlug'
      fullPath: '/boutique/$productSlug'
      preLoaderRoute: typeof BoutiqueProductSlugRouteImport
      parentRoute: typeof BoutiqueRoute
    }
  }
}

interface BoutiqueRouteChildren {
  BoutiqueProductSlugRoute: typeof BoutiqueProductSlugRoute
}

const BoutiqueRouteChildren: BoutiqueRouteChildren = {
  BoutiqueProductSlugRoute: BoutiqueProductSlugRoute,
}

const BoutiqueRouteWithChildren = BoutiqueRoute._addFileChildren(
  BoutiqueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  BoutiqueRoute: BoutiqueRouteWithChildren,
  CoffretSignatureRoute: CoffretSignatureRoute,
  ConseilsRoute: ConseilsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LivraisonRoute: LivraisonRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  CollectionsHaqqiRoute: CollectionsHaqqiRoute,
  CollectionsScentlabRoute: CollectionsScentlabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
